language: cpp
os: linux
dist: bionic

branches:
  except:
  - /^wip-.*$/

addons:
  apt:
    packages: [ 'libsdl2-dev', 'libgtk-3-dev' ]

jobs:
  include:
    - name: "GCC Debug"
      compiler: gcc
      env: BuildType=Debug

    - name: "GCC Release"
      compiler: gcc
      env: BuildType=Release

    - name: "Clang Debug"
      compiler: clang
      env: BuildType=Debug

    - name: "Clang Release"
      compiler: clang
      env: BuildType=Release

before_install:
  - mkdir $HOME/cmake
  - wget -O $HOME/cmake/install.sh https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh
  - bash $HOME/cmake/install.sh --prefix=$HOME/cmake --skip-license --exclude-subdir
  - export PATH="$HOME/cmake/bin:$PATH"
  - cmake --version
  - env

script:
  - mkdir "$TRAVIS_BUILD_DIR/build"
  - cd "$TRAVIS_BUILD_DIR/build"
  - cmake -DCMAKE_BUILD_TYPE="$BuildType" -DBUILD_TOOLS=ON -G "Unix Makefiles" "$TRAVIS_BUILD_DIR"
  - make -l all
  - ctest --output-on-failure
